### ISSUE TITLE
Pseudo-terminal will not be allocated because stdin is not a terminal

### ISSUE THREAD

**Issue by brakonstantin** [JetBrains/commit-status-publisher#3]
TeamCity locks with this error in the log

"Pseudo-terminal will not be allocated because stdin is not a terminal"

even though -t parameter is used in the command line...

**Comment by nd** [comment]
Hi,

I wasn't able to reproduce the issue, but now we configure ssh to not allocate pseudo-terminal. Hope it will fix the problem.
