### ISSUE TITLE
Stash error codes are useless

### ISSUE THREAD

**Issue by disrvptor** [JetBrains/commit-status-publisher#7]
Currently if an error happens during an update of the build status in Stash a very unhelpful error message is shown, for example

> Tests passed: 41; error while publishing a commit status to Stash: org.apache.http.client.HttpResponseException: 40707

If an error happens when POSTing to Stash (such as authentication) it may be reported back as a 4xx response code and a JSON body with the actual error message. Suggested fix is to report the HTTP status code, status line reason and if the body contains JSON then at least the message from the first error (i.e. errors[0].message), but all error messages may be desirable.

Testing against Stash 3.8.1 and TeamCity 9.0.5

[Stash build-status API](https://developer.atlassian.com/static/rest/stash/3.11.1/stash-build-integration-rest.html#idp48624)

**Comment by nd** [comment]
Hi,

please watch/vote for https://youtrack.jetbrains.com/issue/TW-43072.
